# Generated by Django 6.0.5 on 2026-05-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_vendorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Processed', 'Processed'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered')], default='Processed', max_length=20),
        ),
    ]
