# Generated by Django 6.0.5 on 2026-05-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_order_payment_method_order_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('badge', models.CharField(default='PROMO', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('is_active', models.BooleanField(default=True)),
                ('color1', models.CharField(default='0xFF003876', max_length=10)),
                ('color2', models.CharField(default='0xFF0056b3', max_length=10)),
            ],
        ),
    ]
