# Generated by Django 6.0.5 on 2026-05-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_promobanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='discount_percentage',
            field=models.IntegerField(default=0, help_text='Enter discount (e.g., 20 for 20%)'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='is_on_offer',
            field=models.BooleanField(default=False),
        ),
    ]
