# Generated by Django 6.0.5 on 2026-05-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_medicine_discount_percentage_medicine_is_on_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('delivery_address', models.TextField()),
                ('prescription_image', models.ImageField(upload_to='prescriptions/')),
                ('status', models.CharField(choices=[('Pending Verification', 'Pending Verification'), ('Approved - Processing', 'Approved - Processing'), ('Rejected', 'Rejected')], default='Pending Verification', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
