# Generated by Django 6.0.5 on 2026-06-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0009_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
