# Generated by Django 6.0.5 on 2026-06-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0010_vendorprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='has_pos_access',
            field=models.BooleanField(default=False, help_text='Can this vendor use the POS system?'),
        ),
    ]
