# Generated by Django 6.0.5 on 2026-06-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0011_vendorprofile_has_pos_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.CharField(choices=[('First Aid', 'First Aid'), ('Medicines', 'Medicines'), ('Injections', 'Injections'), ('Baby Care', 'Baby Care'), ('Pain Relief', 'Pain Relief'), ('Vitamins', 'Vitamins'), ('Supplements', 'Supplements'), ('Personal Care', 'Personal Care'), ('Devices', 'Devices'), ('General', 'General')], default='General', max_length=100),
        ),
    ]
