# Generated by Django 6.0.5 on 2026-06-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0012_alter_medicine_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
